# Generated by Django 4.2.29 on 2026-03-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_auto_20210410_1253"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="likecomment",
            options={"verbose_name": "Like", "verbose_name_plural": "Likes"},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "Movie", "verbose_name_plural": "Movies"},
        ),
        migrations.AlterModelOptions(
            name="rate",
            options={"verbose_name": "Rating", "verbose_name_plural": "Ratings"},
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="usertagprefer",
            options={
                "verbose_name": "User preference",
                "verbose_name_plural": "User preferences",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=255, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.movie",
                verbose_name="Movie",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.user",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="likecomment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.comment",
                verbose_name="Comment",
            ),
        ),
        migrations.AlterField(
            model_name="likecomment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="likecomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.user",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="collect",
            field=models.ManyToManyField(
                blank=True, to="movie.user", verbose_name="Collectors"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="country",
            field=models.CharField(max_length=255, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="d_rate",
            field=models.CharField(max_length=255, verbose_name="Rating"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="d_rate_nums",
            field=models.IntegerField(verbose_name="Rating count"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(max_length=255, verbose_name="Director"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image_link",
            field=models.FileField(
                max_length=255, upload_to="movie_cover", verbose_name="Cover"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="intro",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="leader",
            field=models.CharField(max_length=1024, verbose_name="Cast"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="num",
            field=models.IntegerField(default=0, verbose_name="Views"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="origin_image_link",
            field=models.URLField(max_length=255, null=True, verbose_name="Image URL"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="movie.tags", verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="years",
            field=models.DateField(verbose_name="Release date"),
        ),
        migrations.AlterField(
            model_name="rate",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="rate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="mark",
            field=models.FloatField(verbose_name="Rating"),
        ),
        migrations.AlterField(
            model_name="rate",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.movie",
                verbose_name="Movie",
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.user",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Tag"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Username"
            ),
        ),
        migrations.AlterField(
            model_name="usertagprefer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usertagprefer",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.tags",
                verbose_name="Tag",
            ),
        ),
        migrations.AlterField(
            model_name="usertagprefer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.user",
                verbose_name="User",
            ),
        ),
    ]
